services:
  gradle:
    image: gradle
    command: >
      bash -c "gradle && gradle build && gradle test && gradle  integrationTest"
    volumes:
      - '$PWD:/home/gradle/project'
    working_dir: /home/gradle/project
    user: gradle
version: '3'
